In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant('Hello')

In [9]:
world = tf.constant(' world')


In [10]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [11]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [12]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [13]:
print(result)

b'Hello world'


In [21]:
a = tf.constant(10)

In [22]:
b = tf.constant(20)

In [23]:
type(a)

tensorflow.python.framework.ops.Tensor

In [24]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [25]:
a+b

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [28]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [29]:
result

30

In [30]:
const = tf.constant(10)

In [31]:
fill_mat = tf.fill((4,4), 10)


In [32]:
myzeros = tf.zeros((4,4))

In [33]:
myones = tf.ones((4,4))

In [34]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [35]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [36]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]


In [37]:
sess = tf.InteractiveSession()

In [38]:
for op in my_ops:
    print(sess.run(op))
    print('**************************')

10
**************************
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
**************************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
**************************
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
**************************
[[-0.19971228 -0.40087885  0.5883126  -0.8875639 ]
 [-0.0999686  -0.18567176  0.7803916   0.37201673]
 [ 1.167813    2.1414332  -0.0937039  -0.00815881]
 [ 0.8946677  -0.7375603   1.1039431   1.6295826 ]]
**************************
[[2.0606101e-01 7.0050251e-01 1.2555838e-02 1.4694417e-01]
 [4.8160446e-01 8.2493293e-01 3.1649005e-01 4.9471855e-05]
 [9.7451508e-01 5.2438176e-01 5.3285599e-01 8.0139244e-01]
 [6.8647420e-01 4.6239269e-01 3.6113811e-01 1.5431786e-01]]
**************************


In [39]:
for op in my_ops:
    print(op.eval())
    print('**************************')

10
**************************
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
**************************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
**************************
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
**************************
[[-0.9540986  -0.464641   -1.0696759   1.2655923 ]
 [ 0.4282243  -0.35867858  0.2872892   0.8045911 ]
 [ 0.9508318   0.01519646 -1.7610064   0.40023014]
 [-0.7814606   0.57757336 -0.07193084  1.2677199 ]]
**************************
[[0.800797   0.03818941 0.22068632 0.75190675]
 [0.6777564  0.8652251  0.11377668 0.03287721]
 [0.6702224  0.7728969  0.7983041  0.47418702]
 [0.6803323  0.3710078  0.8055047  0.5257387 ]]
**************************


In [40]:
a = tf.constant([[1,2],
                 [3,4]])

In [41]:
b = tf.constant([[10], [100]])

In [42]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [43]:
result = tf.matmul(a,b)

In [44]:
sess.run(result)


array([[210],
       [430]])

In [45]:

n1 = tf.constant(1)

In [46]:
n2 = tf.constant(2)


In [47]:
n3 = n1 + n2

In [49]:
with tf.Session() as sess:
    result = sess.run(n3)

In [50]:
print(result)

3


In [51]:
print(n3)

Tensor("add_7:0", shape=(), dtype=int32)


In [52]:
print(tf.get_default_graph())

In [53]:
g = tf.Graph()

In [54]:
print(g)

In [55]:
graph1 = tf.get_default_graph()

In [56]:
graph2 = tf.Graph()


In [57]:
print(graph2)

In [58]:
with graph2.as_default():
    print(graph2 is tf.get_default_graph())

True


In [59]:
print(graph2 is tf.get_default_graph())

False


In [60]:
sess = tf.InteractiveSession()

C:\Users\Gary\Anaconda3\envs\Jupyter-Playground\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [62]:
my_tensor = tf.random_uniform((4,4),0,1)

In [63]:
my_tensor

<tf.Tensor 'random_uniform_2:0' shape=(4, 4) dtype=float32>

In [64]:
my_var = tf.Variable(initial_value=my_tensor)

Instructions for updating:
Colocations handled automatically by placer.


In [65]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [69]:
sess.run(my_var)

array([[0.18592286, 0.56304705, 0.04508662, 0.68050456],
       [0.28228605, 0.5577047 , 0.7996868 , 0.5406654 ],
       [0.40262985, 0.20782518, 0.7533634 , 0.5015569 ],
       [0.18893635, 0.21534693, 0.38704312, 0.32877302]], dtype=float32)

In [67]:
init = tf.global_variables_initializer()

In [68]:
sess.run(init)

In [70]:
ph = tf.placeholder(tf.float32)